tap "cloudfoundry/tap"
tap "git-duet/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "pivotal/tap"

brew "awscli"
brew "cloudfoundry/tap/bbl"
brew "cloudfoundry/tap/bosh-cli"
brew "cloudfoundry/tap/cf-cli"
brew "cloudfoundry/tap/credhub-cli"
brew "direnv"
brew "git"
brew "git-crypt"
brew "git-duet/tap/git-duet"
brew "gnupg"
brew "go"
brew "hub"
brew "jq"
brew "openssl@1.1"
brew "pivotal/tap/pivnet-cli"
brew "python"
brew "terraform"
brew "zsh"

cask "caffeine"
cask "java"
cask '1password'
cask 'discord'
cask 'divvy'
cask 'docker'
cask 'dropbox'
cask 'flycut'
cask 'github'
cask 'iterm2'
cask 'spectacle'
cask 'visual-studio-code'
cask 'zoomus'
