#!/usr/bin/env zsh

set -e

echo "\n📦📦📦📦📦 Installing Go packages 📦📦📦📦📦 \n"

# ginkgo
echo "Getting Ginkgo"
go install github.com/onsi/ginkgo/ginkgo@latest

# cdgo
echo "Getting cdgo"
go install github.com/EngineerBetter/cdgo-cli@latest

# yaml2env
echo "Getting yaml2env"
go install github.com/EngineerBetter/yml2env@latest

# dlv
echo "Getting dlv"
go install github.com/go-delve/delve/cmd/dlv@latest

# pprof
echo "Getting pprof"
go install github.com/google/pprof@latest
