#!/usr/bin/env zsh

set -e

if [ ! -x /Library/Developer/CommandLineTools ]
  then
    echo "Installing Command Line tools"
    xcode-select --install
  else
    echo "Command Line tools ($(xcode-select --version)) already installed, skipping installation"
fi

install_homebrew() {
  if [ ! -x /usr/local/bin/brew ]
  then
    echo "Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo "Homebrew already installed, checking for updates"
    brew update
  fi
}

install_homebrew

echo "Installing brew packages"
brew bundle

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "----------------------------------------------------------------------"
echo "|  🕰 Now would be a good time to update ~/.zshrc and ~/.gitconfig 🕰  |"
echo "----------------------------------------------------------------------"

